suche/authuser/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import authuser.views as authview


urlpatterns = patterns('',   
    url(r'^signin$',authview.signin, name = 'signin'),
    url(r'^signup$',authview.signup, name = 'signup'),
    url(r'^signout$',authview.signout, name = 'signout'),
    url(r'^userinfo$',authview.userinfo, name = 'userinfo'),
    
)

suche/frontend/urls.py
from django.conf.urls import patterns, url

from frontend import views

suche/suche/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import frontend.views as frontendview
import pluginServer.views as plSrv
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'suche.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', frontendview.home, name='homepage'),
    url(r'^autocomplete$',frontendview.autocomplete, name = 'autocomplete'),
    url(r'^search$',frontendview.searchresult, name = 'searchresult'),
    url(r'^cache$',frontendview.websitecache, name = 'websitecache'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^crawler/', include('crawler.urls', namespace = 'crawler')),
    url(r'^plugin/(?P<name>[a-zA-Z0-9_.-]+)/$',plSrv.pluginProcessServer,name='pluginLink'),
	url(r'^auth/', include('authuser.urls', namespace = 'authuser')),
)

suche/frontend/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpRequest
from django.template import RequestContext, loader
from django.core.exceptions import ObjectDoesNotExist
from django import forms
from django.contrib import messages
from linguistic.queryhandler import QueryHandler
from engine.result import SucheResult
from engine.search import SucheSearch
from indexer.models import SucheURL
from crawler.models import Rawdata
from django.shortcuts import get_object_or_404
from plugin.pluginProcess import *

def home(request):
    '''
    This is the search engine home page handler.
    '''

    template = loader.get_template('frontend/home.html')

    query = request.REQUEST.get('q','')
    correctedquery = ''
    parsedquery=''
    if query:
        # if the user entered some text, record it
        correctedquery = QueryHandler.correct_query(query)        
        QueryHandler.register_query(correctedquery)
             
        
    context = RequestContext(request, {
        'title': "Suche",
        'query' : query,
        'correctedquery' : correctedquery,
        'user' : request.user,
        
    })
    return HttpResponse(template.render(context))

def autocomplete(request):
    '''
    Auto complete for suche
    auto completes the user entered sentence
    to test this view,
    http://127.0.0.1:8000/autocomplete?callback=autocomplete&search=a
    '''

    completions = []
    if 'search' in request.REQUEST:
        completions = QueryHandler.get_completions(request.REQUEST['search'])
        resp='<table style="width:100%;" class="text-left">'

        for compl in completions:
            resp=resp+'<tr class="autoRow"><td>'
            compl2=compl.replace(request.REQUEST['search'],'<strong>'+request.REQUEST['search']+'</strong>')
            resp=resp+str(compl2)
            resp=resp+'</tr>'
    resp=resp+"</table>"
    return HttpResponse(resp)

def searchresult(request):
    '''
      returns the search result div
      the url is /searchresult
    '''
    query = request.REQUEST.get('q','')
    query=' '.join(query.split())
    if not query:
        return HttpResponse("Please enter your query")

    search = SucheSearch()
    correct = True

    try:
        if request.GET['force'] == '1':
            correct = False
    except:
        pass
    search.SetQuery(query,correct)
    search.search()
    '''query
    parsing
    '''
    parsedquery=QueryHandler.parse_query(search.correctedquery)
    pluginOp=''
    hasPluginOp=False
        #check if op is to be shown
    if parsedquery[0]==(-1):
        pluginOp='no match'
    else:
        if parsedquery[0].plugin.showsOp:
            hasPluginOp=True
            q=PluginProcessor(parsedquery[0],parsedquery[1])
            pluginOp=q.dispatchandRead()
            if(pluginOp==b'err'):
                hasPluginOp=False
    
    template = loader.get_template('frontend/result.html')

    context = RequestContext(request, {
        'query' : search.query,
        'correctedquery' : search.correctedquery,
        'corrected' : search.isQueryCorrected,
        'results':search.results,
        'resultcount' : len(search.results),
        'totalresults': search.totalresult,
        'hasresult' : True if len(search.results) > 0 else False,
        'hasPluginOp':hasPluginOp,
        'pluginOp':pluginOp,
    })
    return HttpResponse(template.render(context))
def websitecache(request):
    url = request.GET.get('page','')
    if len(url) > 4:
        urlobj = get_object_or_404(SucheURL, url=url)
        data = get_object_or_404(Rawdata,url = urlobj)
        return HttpResponse(data.old_data)
    # show 404 error page
    raise Http404

suche/frontend/templates/frontend/home.html
{% extends "pages/__base.html" %}
{% load staticfiles %}

{% block body %}
<style type="text/css">
    .autoRow
    {
	width:100%;
	height:25px;
    }
</style>
    
    <div class="navbar navbar-static-top navbar-inverse" style="margin:0">
    <div class="navbar-inner" style="color:#ffffff">
         <br>
        {% if user.is_authenticated %}
         &nbsp;&nbsp  <strong> Hi, {{ user }} ! </strong>
         <div class="pull-right">
         
          <a style="color:#ffffff"  href="{% url 'authuser:signout' %}">Logout</a> | <a style="color:#ffffff"  href="{% url 'authuser:userinfo' %}">Settings</a>
         </div>
        {% else %}
         <div class="pull-right">
          <br>
          <a style="color:#ffffff" href="{% url 'authuser:signin' %}">Login</a> | <a style="color:#ffffff" href="{% url 'authuser:signup' %}">Signup</a>
          </div>
        {% endif %}       
        
    </div>
    </div><!--user authentication part -->


    <div class="row" style="padding-bottom: 20px;top:-20px" id="bg">
        <div class="container text-center">
        
            <div class="row text-center">
                <!--logo -->
                <div class="row text-center" id="bg">
                <div class="col-md-12 text-center" id="logo">
                  <a href="{% url 'homepage' %}"><img  src="{% static 'images/logo.png' %}" class="img-responsive" style="margin: 0 auto;" id="logo1"/></a>
                </div>
                </div>
                <!--logo -->
                <form class="row" id="search_form" action="/" method="GET">
                    <div class="input-group">
                      <div class="input-group-addon"><span class="glyphicon glyphicon-search"></span></div>
                      <input type="text" class="form-control" placeholder="Search Query" id="search" name = "q" style="height:50px"  autocomplete="off"/>
                      <div class="input-group-btn"><input type="submit" value="Search" class="btn btn-primary" style="height:50px; width:100px" id="submitBtn"></div>
                    </div>
                </form>
                <!-- autocomplete box -->
                <div id="box" 
                      style="display: block;
                      left:150px;position: absolute;
                      border-style: solid;
                      float:right;
                      z-index: 10000;
                      border-width: thin;
                      border-color: #eee;
                      box-shadow: 3px 3px 3px #eee;
                      background-color: #fff;"> 
                </div>


                {% if query %}
                  <br/><br/><p>Showing result for &quot;<strong>{{ correctedquery }} </strong> &quot;
                  {% if correctedquery != query  %} 
                    Show instead for &quot;<strong><a id="searchinstd" href="google.com">{{ query }} 
                  {% endif %}
                  </a> </strong>&quot;</p><br>Parsed:<b>{{parsedquery}}</b>
                {% endif %}

            </div>
          </div>
    </div>
                  
    
    <div class="container text-left" style="padding-top: 10px" id="searchResult">
  
    </div>

<script>
var state=0;
//for keyup keydown
var index=-1;
//flag for autocomplete
var autoState=0;
$(function(){
    
   $('#search').focus(); 
   $('#search').keyup(function(e){
     if(e.keyCode!=13 && e.keyCode!=38 && e.keyCode!=40)
     {
        startcompletion();
     }
   });
   //pressing of search instead for
   
   $('body').on("click",'#searchinstd',function(e){

        e.preventDefault();
        //send request
         $.get("/search?q="+encodeURIComponent($('#search').val())+"&force=1",function(op){              
                   $("#searchResult").fadeOut("fast",function()
                    {
                            
                        $("#searchResult").html(op).fadeIn("fast");
                    });              
                });
    
   });
});

function startcompletion() {
    var search = $('#search').val()
    //alert('aaa');
    var data = {
        callback:"autocomplete",
        search: search
    };
    $.get('/autocomplete',data,function(op){
        displayAutocomplete(op);
    });
    

}



$(function() {
$('#search_form').submit(function(event) {
    // we have to load the search result with ajax later
//this function will slide the division "topspace" up and 
//display the result.
    event.preventDefault();
    //alignAutoSize();
    var vall=$('#search').val();
    if (vall!="" && state==0) {
        //code
          
          $( "#searchaa" ).autocomplete ("close");
          hideAutocomplete();
          $('#logo').animate({
              "width":"300px",
              
           
          },"slow");
          //animate textbox
          $('#search').animate({"height":"40px"},"slow");
          $('.input-group-addon').animate({"opacity":"0"},"slow");
          $('#submitBtn').animate({"height":"40px"},"slow");
          
          //animate bg color
          $('#bg').animate({
                 "backgroundColor":"#eee",
                 "left":"0px"
              
          },"slow");
          
          $('#logo1').css({"margin": "0 auto" } );
          
          state=1;
          
        
    }

        if (vall!="" && state==1) {
        hideAutocomplete();
        //do the get request

            $.get("/search?q="+encodeURIComponent(vall),function(op){              
               $("#searchResult").fadeOut("fast",function()
                {
			
                    $("#searchResult").html(op).fadeIn("fast");
                });              
            });
        
    }

});
//to restore on empty


});

</script>

<script>
    //autoComplete box
function alignAutoSize()
{
   var sizee=$('#search').width();
   $('#box').width(sizee);
   var leftt=$('#box').offset().left;
   leftt=leftt-30;
   $('#box').offset({left:leftt});       
    
}
function hideAutocomplete() {
    //code
    $('#box').fadeOut("fast");
    autoState=0;
}
function showAutocomplete() {
    //code
    $('#box').fadeIn("fast");
    autoState=1;
}

//display autocomplete box and display data
function displayAutocomplete(data) {
var prevData=$('#box').text();
if(prevData!=data)
{
    var vall=$('#search').val();
    if (vall!="")
    {
        $("#box").html(data);
        $("#box").attr("style","display: block;left:150px;position: absolute;border-style: solid;float:right;z-index: 10000;border-width: thin;border-color: #eee;box-shadow: 3px 3px 3px #eee;background-color: #fff");
alignAutoSize();       
if(autoState!=1)
       { 
       
       if ($("#search").is(":focus")) {
            // display box with data
            showAutocomplete();
        }
       }
    }
    else
    {
      hideAutocomplete();
    }

}
   
}
 $(function(){
    alignAutoSize();
    //on focus out hide
    $('#search').focusout(function(){
        hideAutocomplete();
    });
    $('#box').on("mouseenter", ".autoRow", function() {
       $(this).animate({"backgroundColor":"#eee"},10);
    });

    $('#box').on("mouseleave", ".autoRow", function() {
       $(this).animate({"backgroundColor":"#fff"},10);
    });
    $('#box').on("click", ".autoRow", function() {
       var text=$(this).text();
       $("#search").val(text);
    });
    
    
    //arrow handling
    $(document).keydown(function(e){
       
        
            switch (e.keyCode)
            {
                case 40:
                    
                                  
                     $('.autoRow').eq(index).animate({"backgroundColor":"#fff"},10);
                     var size=$('.autoRow').length;
                    
                     index++;
                    if (index>size) {
                        //code
                        index=0;
                     }
                     $('.autoRow').eq(index).animate({"backgroundColor":"#eee"},10);
                      
                    break;
                case 38:
                    
                                         
                     $('.autoRow').eq(index).animate({"backgroundColor":"#fff"},10);
                     var size=$('.autoRow').length;
                     index--;
                     if (index<0) {
                        //code
                        index=size;
                     }      
                      
                     $('.autoRow').eq(index).animate({"backgroundColor":"#eee"},10);
                    break;
                
            }
    });
    
    $(document).keydown(function(e){
        if (autoState==1) {
            var length=$('.autoRow').length;
            if (index>=0 && index<length) {
                if(e.keyCode==13){
                e.preventDefault();
                var text=$('.autoRow').eq(index).text();
                $("#search").val(text);
		 hideAutocomplete();   
                index=-1;
               
             }
                
            }
        }
        
    });
 
 });
 
</script>
{% endblock body %}

suche/frontend/templates/frontend/result.html
  <span style="font-family:Verdana, Geneva, sans-serif; font-size:14px;font-weight:lighter">
    Searching for <strong> {{ correctedquery }}</strong>. {% if corrected %} Search instead for<strong><a id="searchinstd" href=""> {{ query }}</a> </strong>{% endif %}<br/>
    {% if hasresult %}
    Showing 1-{{ resultcount }} of about {{ totalresults }} results<br/>
    {% endif %}
  </span>
  <hr>
  {% if hasPluginOp %}
  <div class="row">
  <div class="col-md-12">
    
    {% autoescape off %}
    {{pluginOp}}
    {% endautoescape %}
</div></div>
{%endif%}
<br>
{% if hasresult %}
<div class="row">
  {% for result in results %}
  
  
  <div>
    <a href="{{ result.fullurl }}" style="text-decoration:none" target="_blank">
      <span style="font-family:Arial, Helvetica, sans-serif; color:#0a5c83;">
        {% autoescape off %}
        {{ result.highlightedtitle }}
        {% endautoescape %}
      </span>
    </a>
  </div>


  <div>
    <span style="font-family:Arial, Helvetica, sans-serif; color:#070; font-size:12px">
      {% autoescape off %}
      {{ result.highlightedurl }}
      {% endautoescape %}
    </span>
  </div>

  <div>
    <span style="font-family:Verdana, Geneva, sans-serif; font-size:14px;font-weight:lighter">
      {% autoescape off %}
      {{ result.highlightedbody }}
      {% endautoescape %}
    </span>
  </div>

  <div>
    <span style="font-family:Arial, Helvetica, sans-serif; color:#333; font-size:12px">
      <a href="{% url 'websitecache' %}?page={{result.fullurl | urlencode }}&query={{correctedquery | urlencode}}" target="_blank">Cached Page</a>
    </span>
  </div>

  

</div>
</br>
{% endfor %}
{% else %}
<div>Sorry! No result was found for <strong> {{ correctedquery }}</strong> </div>
</div>
{% endif %}